server:
  port: 9000
spring:
  profiles:
    active:
      # This profile is active by default to avoid accidental leaks of credentials.
      # Local development Kafka installations can be used without authentication (see README.md).
      # This setting can be overridden in command line with '--spring.profiles.active=none'.
      - "secure"
  kafka:
    topic:
      avro: my-test-topic
    properties:
      session:
        timeout:
          ms: 45000
      bootstrap.servers: ${KAFKA_HOST}
    consumer:
      bootstrap.servers: ${KAFKA_HOST}
      group.id: group_id
      auto.offset.reset: earliest
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schema:
        registry:
          url: ${KAFKA_REGISTRY_HOST}
      specific:
        avro:
          reader: true
    producer:
      bootstrap.servers: ${KAFKA_HOST}
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      schema:
        registry:
          url: ${KAFKA_REGISTRY_HOST}
